on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🟢 Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"

      - name: 📄 Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: 📦 Install and build
        run: |
          npm ci
          npm run build

      - name: 🚀 Deploy to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ".output/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
